before_install:
  - sudo apt-get install -y linkchecker

sudo: false

language: ruby

rvm:
  - 2.3.3
  - 2.4.0

cache: bundler
script: ./build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: build
  committer_from_gh: true
  repo: meter-io-docs/meter-io-docs.github.io
  on:
    branch: master
